import type { Metadata } from "next";
import "./globals.css";
import SessionProvider from "@/components/layout/session-provider.layout";
import { GeistSans } from "geist/font/sans";
import { cn } from "@/lib/utils/tailwind.utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body
          className={cn(
            "antialiased flex flex-col w-full grow",
            GeistSans.className
          )}
        >
          {children}
        </body>
      </html>
    </SessionProvider>
  );
}
